### ISSUE TITLE
FATAL ERROR: all events are one day off (-1 day in calendar)

### ISSUE THREAD

**Issue by crysman** [Davepar/gcalendarsync#72]
I am unable to solve this FATAL ERROR: **all events are one day off** (-1 day in calendar) even though both sheet and calendar use the same GMT offset (+2):

Google Sheet:
![image](https://user-images.githubusercontent.com/5269350/91998652-c9a35780-ed3b-11ea-89c2-654282b40824.png)

![image](https://user-images.githubusercontent.com/5269350/91998991-30c10c00-ed3c-11ea-8200-ca03be08c2c0.png)

![image](https://user-images.githubusercontent.com/5269350/91999171-5f3ee700-ed3c-11ea-925e-2c7a839d7a85.png)
![image](https://user-images.githubusercontent.com/5269350/91999224-72ea4d80-ed3c-11ea-9f45-c80dfe7e911d.png)

Extension settings:
![image](https://user-images.githubusercontent.com/5269350/91999953-4256e380-ed3d-11ea-9cd3-45ee1c37f324.png)

Google Calendar:
![image](https://user-images.githubusercontent.com/5269350/91998724-de7feb00-ed3b-11ea-86ee-2ad373f865e7.png)

![image](https://user-images.githubusercontent.com/5269350/91999719-fdcb4800-ed3c-11ea-836b-ef6ed56401d7.png)

BTW, I must select "Athens" in Google Sheets, because "Prague" is for some reason listed incorrectly as GMT+1. When I select "Prague" in both, however, problem doesn't get fixed anyways.

Any ideas? Thanks!

**Comment by crysman** [comment]
Hello, please, any info if this will be fixed? I mean: I can make all our events one day off, but that will make it unstable - when you release a fix, we will get one day off... Would be helpful if I knew realistically, what will happen in next 2 weeks, whether:

1. I forcefully make all our events one day off (offset)
1. Wait 2 weeks to have it fixed by developer(s) and so have it fixed by fixing the bug

Thanks a lot

**Comment by Davepar** [comment]
Sorry for these issues. It was partly caused by Google always assuming US/Pacific time zone. This should be fixed now. Re-open the issue if it isn't.

**Comment by crysman** [comment]
Unfortunately, there is an error now:
![image](https://user-images.githubusercontent.com/5269350/92896014-4a3d1480-f41c-11ea-9855-e7c134ca6189.png)
![image](https://user-images.githubusercontent.com/5269350/92896124-650f8900-f41c-11ea-9166-d826a5dcedb9.png)

and calendar is not synced :(

**Comment by crysman** [comment]
@Davepar thanks for fixing the `TypeError`, unfortunately the **original issue persists - in Google Calendar, all events are -1 day off ** :disappointed:

**Comment by itluzanky** [comment]
To make it easier for you to debug, here are the resources:

sheet:
https://docs.google.com/spreadsheets/d/1HvsaNjmquyga7ruJmEEPOLrPhbY8b4vRRFu99OdSxgw/edit#gid=901722093

calendar:
c_0vtp5ksq7553alumb371avgkqk@group.calendar.google.com

please let us know soon what is going on here... thanks a lot!

**Comment by Davepar** [comment]
I can't seem to re-create this problem on my computer. I'm in the US/Pacific time zone (-7) and have no issues. I've set everything I can think of to New Zealand time (+12) which is a day ahead of me, and still have no issues syncing either way. I've found 4 different places to set time zone, in the sheet, in the specific calendar, in Calendar general settings, and on my computer.

I was able to make everything off by a day (including non-all day events) by setting both Calendar time zones to something different than my computer time zone. You have all 4 places I mentioned above set to the same time zone, right?

**Comment by Davepar** [comment]
Or this is interesting, the dates seem to actually start going off by one day when I set the "secondary time zone" in Calendar settings. When I unchecked "secondary time zone", still off by one day. It wasn't until I actually changed the secondary time zone to the same as my primary time zone that it was fixed. That seems like a bug in Calendar.

**Comment by Davepar** [comment]
I might have figured out the problem. I just uploaded a new version that uses the spreadsheet's time zone for all-day events. Hopefully that works for you.

**Comment by itluzanky** [comment]
@Davepar thanks a lot - at last, this has fixed the problem ... well, almost :( - see #77

**Comment by itluzanky** [comment]
might be closed now I think
https://github.com/Davepar/gcalendarsync/issues/76#issuecomment-695979460
